import { defineConfig } from '@playwright/test';                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                          
  export default defineConfig({                                                                                                                                                                                                                                               
    testDir: './tests',                                                                                                                                                                                                                                                       
    timeout: 60_000,                                                                                                                                                                                                                                                      
    retries: 2,                                                                                                                                                                                                                                                               
    fullyParallel: true,                                                                                                                                                                                                                                                  
    workers: 5,                                                                                                                                                                                                                                                           
    reporter: [                                                                                                                                                                                                                                                           
      ['html', {                                                                                                                                                                                                                                                          
        outputFolder: 'playwright-report',                                                                                                                                                                                                                                
        open: 'never'                                                                                                                                                                                                                                                     
      }],                                                                                                                                                                                                                                                                 
      ['blob', { outputDir: 'blob-report' }], // Blob reporter for merging                                                                                                                                                                                                
      ['json', { outputFile: './playwright-report/report.json' }],                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                          
      ['@testdino/playwright', {                                                                                                                                                                                                                                          
         token: process.env.TESTDINO_TOKEN,                                                                                                                                                                                                                               
        serverUrl: 'https://staging-api.testdino.com',                                                                                                                                                                                                                    
      }],                                                                                                                                                                                                                                                                 
    ],                                                                                                                                                                                                                                                                    
    projects: [                                                                                                                                                                                                                                                           
      {                                                                                                                                                                                                                                                                   
        name: 'chromium',                                                                                                                                                                                                                                                 
        use: {                                                                                                                                                                                                                                                            
          browserName: 'chromium',                                                                                                                                                                                                                                        
          baseURL: 'https://storedemo.testdino.com',                                                                                                                                                                                                                      
          headless: true,                                                                                                                                                                                                                                                 
        },                                                                                                                                                                                                                                                                
      },                                                                                                                                                                                                                                                                  
    ],                                                                                                                                                                                                                                                                    
  });             